version: '3.7'

services:
  database:
    image: postgres:13.4
    container_name: ponto_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=newm
      - POSTGRES_PASSWORD=newm
      - POSTGRES_DB=ponto

  app:
    image: ambientum/php:7.3-nginx
    container_name: ponto_newm
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - database
