name: Deploy in Contabo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copying Files
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'npm'
      
      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build
    
