name: Deploy in Contabo

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Copying Files
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 17
        cache: 'npm'
      
    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build
        
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSHHOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "./frontend/dist"
        target: "./taskfy-frontend"
        
