name: Deploy in Contabo

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Copying Files
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
      
    - name: Build Frontend
      working-directory: ./frontend
      run: npm install && npm run build
        
    - name: Send Files to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        rm: true
        strip_components: 3
        source: "./frontend/dist/."
        target: "./taskfy-frontend"
        
    - name: Authenticating in Portainer
      id: portainer
      uses: satak/webrequest-action@master
      with:
        url: ${{ secrets.PORTAINER_HOST }}/api/auth
        method: POST
        payload: '{"username":"${{ secrets.PORTAINER_USERNAME }}","password":"${{ secrets.PORTAINER_PASSWORD }}"}'
        
    - name: Saving Portainer Token
      run: |
        $PORTAINER_TOKEN = '${{ fromJSON(steps.portainer.outputs.output.jwt) }}'
        echo $PORTAINER_TOKEN

    - name: Restarting Portainer Stack
      uses: satak/webrequest-action@master
      with:
        url: ${{ secrets.PORTAINER_HOST }}/api/stacks/${{ secrets.PORTAINER_STACK_ID }}/stop
        method: POST
        headers: '{"Authorization": "Bearer $PORTAINER_TOKEN"}'
        
  sonarqube:
    name: Sonarqube
    runs-on: ubuntu-latest
    steps:
    - name: Copying Files
      uses: actions/checkout@v3
      
    - name: Running Sonar Scanner
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
        
