name: Deploy in Contabo

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Copying Files
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
      
    - name: Build Frontend
      working-directory: ./frontend
      run: npm install && npm run build
        
    - name: Send Files to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        rm: true
        source: "-r ./frontend/dist"
        target: "./taskfy-frontend"
        
