name: Deploy Test Environment

on:
  push:
    branches:
      - "feature-v[0-9].[0-9]+"

jobs:
  deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Copying Files
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Installing Backend Dependencies
        working-directory: ./
        run: composer install

      - name: Build And Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: brenoxavier/taskfy-backend:latest

      - name: Setting Up Environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22
          script: |
            podman stop taskfy_backend
            podman rm taskfy_backend
            podman run --name taskfy_backend --pull=always --restart=unless-stopped --quiet -d -p 30000:8080 --network taskfy -v ./docker/volumes/taskfy/backend:/var/www/php docker.io/brenoxavier/taskfy-backend:latest
            podman exec taskfy_backend php artisan migrate --force
